name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        npm ci
        npm run build --if-present
        npm run test --if-present

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          node_modules/
          host.json
          package.json
          package-lock.json
          azure.yaml
          infra/
          local.settings.json.example

  deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: development
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Download build artifacts'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions (Development)'
      uses: Azure/functions-action@v1
      with:
        app-name: 'ukg-sync-backend-5rrqlcuxyzlvy'
        slot-name: 'production'
        package: .
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION || 'centralus' }}

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Download build artifacts'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions (Production)'
      uses: Azure/functions-action@v1
      with:
        app-name: 'ukg-sync-backend-63mxjgaoxm2c4'
        slot-name: 'production'
        package: .
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION || 'centralus' }}
