name: PR Validation

on:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install Dependencies'
      run: |
        npm ci
        npm run build

    - name: 'Run Linting'
      run: npm run lint

    - name: 'Run Tests'
      run: npm run test

    - name: 'Security Audit'
      run: npm audit --audit-level=moderate

    - name: 'Check for TypeScript Errors'
      run: npx tsc --noEmit
